"""Add utm_campaign field to Content model

Revision ID: 3350d6bf37b0
Revises: 580baa56d94a
Create Date: 2025-05-20 00:47:38.652889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3350d6bf37b0'
down_revision = '580baa56d94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_campaign', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('utm_campaign')

    # ### end Alembic commands ###
