"""Remove content_type field from Content model

Revision ID: 379f7febc7d2
Revises: 7c6f362d908e
Create Date: 2025-05-10 12:32:10.142038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379f7febc7d2'
down_revision = '7c6f362d908e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
