"""Change string fields to TEXT in Share model

Revision ID: 40777968a2bf
Revises: 87112ad29060
Create Date: 2025-05-11 14:51:00.932583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40777968a2bf'
down_revision = '87112ad29060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('post_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('post_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
