"""Add native LinkedIn token fields to User model

Revision ID: 4b5c44ab333f
Revises: 6e0a03d5d72c
Create Date: 2025-05-21 10:18:53.846900

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b5c44ab333f"
down_revision = "6e0a03d5d72c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("linkedin_native_id", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("linkedin_native_access_token", sa.Text(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("linkedin_native_refresh_token", sa.Text(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("linkedin_native_token_expires_at", sa.DateTime(), nullable=True)
        )
        batch_op.create_unique_constraint(
            "uq_users_linkedin_native_id", ["linkedin_native_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_linkedin_native_id", type_="unique")
        batch_op.drop_column("linkedin_native_token_expires_at")
        batch_op.drop_column("linkedin_native_refresh_token")
        batch_op.drop_column("linkedin_native_access_token")
        batch_op.drop_column("linkedin_native_id")

    # ### end Alembic commands ###
