"""Add slack_id to User model

Revision ID: 4ce17c278a3c
Revises: 3350d6bf37b0
Create Date: 2025-05-20 12:27:51.527374

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ce17c278a3c"
down_revision = "3350d6bf37b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slack_id", sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint("uq_users_slack_id", ["slack_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_slack_id", type_="unique")
        batch_op.drop_column("slack_id")

    # ### end Alembic commands ###
