"""Add copy field to Content model

Revision ID: 580baa56d94a
Revises: e9e4c3d4c3a0
Create Date: 2025-05-17 16:40:30.122965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580baa56d94a'
down_revision = 'e9e4c3d4c3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('copy')

    # ### end Alembic commands ###
