"""Add is_admin field to User model

Revision ID: 672f17037cfe
Revises: dd6e188ecf40
Create Date: 2025-05-09 22:27:13.606403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672f17037cfe'
down_revision = 'dd6e188ecf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
