"""Remove author field from Content model

Revision ID: 7c6f362d908e
Revises: 1706446bbca2
Create Date: 2025-05-10 12:31:30.011430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6f362d908e'
down_revision = '1706446bbca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
