"""Add example_social_posts to User model

Revision ID: 87112ad29060
Revises: merge_heads
Create Date: 2025-05-10 20:42:03.092373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87112ad29060'
down_revision = 'merge_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_social_posts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('example_social_posts')

    # ### end Alembic commands ###
