"""Add context field to Content model

Revision ID: 8e3bbc9f262e
Revises: e0fba490788c
Create Date: 2025-05-10 12:22:07.146298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3bbc9f262e'
down_revision = 'e0fba490788c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('posts')
    op.drop_table('manual_content')
    op.drop_table('videos')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('context')

    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('excerpt', sa.TEXT(), nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('channel_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('channel_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('publish_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('manual_content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('excerpt', sa.TEXT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('publish_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('episode_number', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('player_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('publish_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
