"""Simplify ManualContent model to only require URL and content type

Revision ID: 963e028232ac
Revises: 672f17037cfe
Create Date: 2025-05-10 10:59:19.798179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963e028232ac'
down_revision = '672f17037cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_content', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('title')
        batch_op.drop_column('content')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
