"""Initial schema from current models

Revision ID: e9e4c3d4c3a0
Revises: 
Create Date: 2025-05-13 12:06:34.809922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e4c3d4c3a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.String(length=20), server_default=sa.text("'password'"), nullable=False),
    sa.Column('okta_id', sa.String(length=100), nullable=True),
    sa.Column('linkedin_authorized', sa.Boolean(), nullable=False),
    sa.Column('linkedin_token', sa.Text(), nullable=True),
    sa.Column('autonomous_mode', sa.Boolean(), nullable=False),
    sa.Column('example_social_posts', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('okta_id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('scraped_content', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name='fk_content_submitted_by_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    op.drop_table('content')
    op.drop_table('users')
    # ### end Alembic commands ###
