"""Add named foreign key for submitted_by_id and remove source field

Revision ID: ec798e612e0c
Revises: 379f7febc7d2
Create Date: 2025-05-10 12:54:57.604855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec798e612e0c'
down_revision = '379f7febc7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_content_submitted_by_id_users', 'users', ['submitted_by_id'], ['id'])
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_content_submitted_by_id_users', type_='foreignkey')
        batch_op.drop_column('submitted_by_id')

    # ### end Alembic commands ###
